### ISSUE TITLE
Is publishing_api:publish_special_routes rake task still used/needed?

### ISSUE THREAD

**Issue by floehopper** [alphagov/manuals-frontend#219]
It seems odd that a front-end app contains a [rake task which writes to the Publishing API](https://github.com/alphagov/manuals-frontend/blob/master/lib/tasks/publishing_api.rake).

**Comment by tijmenb** [comment]
This looks like a one-time redirect.  It can definitely be removed.

Looks like it's run run every time this app is deployed: https://github.com/alphagov/govuk-app-deployment/blob/1359c74964d39f376438caf8c8f72578616b3b3e/manuals-frontend/config/deploy.rb#L21. That call needs to be removed first, otherwise your deploys will fail.

**Comment by cbaines** [comment]
If the content which it creates is still used, I think it should be kept. It can be useful for local development when you want to setup the app (I've used similar rake tasks in other apps).

**Comment by tijmenb** [comment]
We'll keep the rake task around for visibility.
